version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      svelte:
        patterns:
          - "svelte*"
          - "@sveltejs/*"
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
      typescript:
        patterns:
          - "typescript"
          - "tslib"
          - "@tsconfig/*"